name: ESLint Check

on:
  pull_request:
    branches: main 

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0' # Match your Prettier workflow Node.js version

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run ESLint to check for linting issues
      - name: Run ESLint Check
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
